---
development:
  cloud_name: ztchia
  api_key: '884726311218725'
  api_secret: lHGL3r3YNo3elmxME_PVe7-4mRY
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: ztchia
  api_key: '884726311218725'
  api_secret: lHGL3r3YNo3elmxME_PVe7-4mRY
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: ztchia
  api_key: '884726311218725'
  api_secret: lHGL3r3YNo3elmxME_PVe7-4mRY
  enhance_image_tag: true
  static_image_support: false